name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run weekly on Sundays at 2 AM UTC to get base image updates
    - cron: '0 2 * * 0'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: repo
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image (smoke test)
        if: github.event_name != 'pull_request'
        run: |
          # Test Node.js installation
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest node --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest npm --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest yarn --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest pnpm --version
          
          # Test Python installation
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest python3 --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest pip --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest poetry --version
          docker run --rm ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}:latest pipenv --version

      - name: Clean up old container images
        if: github.event_name != 'pull_request'
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'coder-x-base'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: false

      - name: Generate build summary
        if: github.event_name != 'pull_request'
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: \`${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Cleanup**: Keeping latest 3 versions, older ones deleted" >> $GITHUB_STEP_SUMMARY
